name: fiper
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - omegaconf
  - scipy
  - tqdm
  - hydra-core
  - scikit-learn
  - matplotlib
  - pandas
  - zarr
