defaults:
  - base

# Whether to use the same cell size for all dimensions
single_cellsize: False
# The factor by which to multiply the working area to determine the cell size
cellsize_factor: 0.03

required_tensors:
  - "action_preds"

required_actions:
  - "position"

optional_actions: []


hparams: 
  model:
    cellsize_factor: ${eval.cellsize_factor}
    single_cellsize: ${eval.single_cellsize}


normalize_tensors: 
  action_preds: False