defaults:
  - base

name: pretzel
description: "Form a pretzel shape from a rope"
type: "realworld"

environment:
  name: "PretzelEnv-v0"
  ts: 0.2
  max_episode_steps: 100
  fail_on_error: false
  fail_after_steps: false

observation_space:
  observation_type: "rgb"
  rgb:
    format: "(H, W, C)"
    shape: (240, 320, 3)
  observation_dim: 3

state_space:
  state_dim: 5
  state_types: "continuous"
  state_mapping:
    position: [0, 1, 2]
    rotation: [3, 4]
    velocity: 

action_space:
  action_type: "continuous"
  actions:
    dim: 5
    action_mapping:
      position: [0, 1, 2]
      rotation: [3, 4]
      velocity: 
  action_pred:
    format: "(batch_size, prediction_horizon, action_dim)"
    action_prediction_horizon: 16
    batch_size: 30
    shape: (${task.action_space.action_pred.batch_size}, ${task.action_space.action_pred.action_prediction_horizon}, ${task.action_space.actions.dim})
  action_execution_horizon: 4
