defaults:
  - base

name: "push_t"
description: "Push an T-shaped object to a target position"
type: simulation

environment:
  name: "PushTEnv-v0"
  ts: 0.2
  max_episode_steps: 300
  fail_on_error: true
  fail_after_steps: 300

observation_space:
  observation_type: "rgb"
  rgb:
    format: "(H, W, C)"
    shape: (512, 512, 3)
  observation_dim: 3

state_space:

action_space:
  action_type: "continuous"
  actions:
    dim: 3
    action_bounds:
    action_mapping:
      position: [0, 1, 2]
      rotation: 
      velocity: 
  action_pred:
    format: "(batch_size, prediction_horizon, action_dim)"
    action_prediction_horizon: 16
    batch_size: 256
    shape: (${task.action_space.action_pred.batch_size}, ${task.action_space.action_pred.action_prediction_horizon}, ${task.action_space.actions.dim})
  action_execution_horizon: 8
  