defaults:
  - base

name: "sorting"
description: "Push two blocks into their respective color-matching bin"
type: simulation
environment:
  ts: 0.035
  max_episode_steps: 300
  fail_on_error: true
  fail_after_steps: 300

action_space:
  action_type: "continuous"
  actions:
    dim: 3
    action_bounds:
      low: -1.0
      high: 1.0
    action_mapping:
      position: 
      rotation: 
      velocity: [0, 1, 2]
  action_pred:
    format: "(batch_size, prediction_horizon, action_dim)"
    shape: (32, $(task.action_space.action_pred.action_prediction_horizon), ${task.action_space.actions.dim})
    action_prediction_horizon: 8
  action_execution_horizon: 4
  
  