defaults:
  - base

name: "stacking"
description: "Stack objects on top of each other"
type: simulation
environment:
  ts: 0.035
  max_episode_steps: 300
  fail_on_error: true
  fail_after_steps: 300

state_space:
  state_dim: 8
  state_types: 
  state_bounds: 
  state_mapping:
    joint_pos: [0, 1, 2, 3, 4, 5, 6]
    gripper: [7]

action_space:
  action_type: "continuous"
  actions:
    dim: 21
    action_bounds:
      low: -1.0
      high: 1.0
    action_mapping:
      position: [0, 1, 2]
      rotation: [3, 4, 5]
      velocity: 
      joint_pos: [6, 7, 8, 9, 10,11,12]
      joint_velocity: [13, 14, 15, 16, 17,18,19]
      gripper: [20]
  action_pred:
    format: "(batch_size, prediction_horizon, action_dim)"
    shape: (32, $(task.action_space.action_pred.action_prediction_horizon), ${task.action_space.actions.dim})
    action_prediction_horizon: 8
  action_execution_horizon: 4
  
  